AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  snsBudgetsEnricher:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: An Amazon SNS trigger that logs the message pushed to the SNS topic.
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::918729401437:role/service-role/Lambda-SNS-Budgets-Enricher'
      Runtime: python2.7
      Timeout: 3
